joint_cohort: gvcfs.tsv
species: horse
ref: goldenPath
date: ''
bucket: ref
alias: s3
profile: slurm
sif: /users/7/dimml002/.sif/wags.sif
conda_envs:
  qc: bcftools
anchor_type: nruns
nrun_length: 50
interval_length: 10000000
batch_size: 50
ref_fasta: /home/refgen/horse/goldenPath/goldenPath.Ec_build-3.0_wMSY.fa
ref_dict: /home/refgen/horse/goldenPath/goldenPath.Ec_build-3.0_wMSY.dict
ref_gtf: /home/refgen/horse/goldenPath/MISSING.gtf
tmp_dir:
  sites_only_gather_vcf: /path/to/.sites_gather
  unfilt_gather_vcf: /path/to/.unfilt_gather
snp_recalibration_tranche_values:
- '100.0'
- '99.95'
- '99.9'
- '99.5'
- '99.0'
- '98.0'
- '97.0'
- '96.0'
- '95.0'
- '94.0'
- '93.0'
- '92.0'
- '91.0'
- '90.0'
snp_recalibration_annotation_values:
- QD
- MQRankSum
- ReadPosRankSum
- FS
- MQ
- SOR
- DP
snp_filter_level: '99.0'
indel_recalibration_tranche_values:
- '100.0'
- '99.95'
- '99.9'
- '99.5'
- '99.0'
- '98.0'
- '97.0'
- '96.0'
- '95.0'
- '94.0'
- '93.0'
- '92.0'
- '91.0'
- '90.0'
indel_recalibration_annotation_values:
- FS
- ReadPosRankSum
- MQRankSum
- QD
- SOR
- DP
indel_filter_level: '99.0'
coverage_sites: ''
phasing: false
link_map: /home/refgen/horse/goldenPath/MISSING.linkage.map
